### PR TITLE
adds stratton photo to careers page

### LINKED ISSUE #585: Add Team Photo to Careers Page
Can we please add this at the top of the careers page? Think it would be a good image to land on first thing. 🙏 

blockstack pbc group-6

### PR DESCRIPTION
**Pull request by hstove**
This is to close #585 

screen shot 2018-07-18 at 5 46 55 am

### CODE REVIEW

**Comment by wbobeirne** [comment]
Can we compress this photo down a bit? 1.88mb can take a long time on a mobile connection.

**Comment by hstove** [comment]
@wbobeirne do you have a go-to tool for compressing photos for web?

**Comment by aulneau** [comment]
@hstove I have implemented a compression tool in the new website!

**Comment by aulneau** [comment]
I'll also be adding this to the new site (which will take over this page)

**Comment by hstove** [comment]
@aulneau awesome. Can we just pull this photo into the new site?

**Pull request closed without merging**
