### PR TITLE
Hamburger nav

### PR DESCRIPTION
**Pull request by estermer**
#289

### CODE REVIEW

**Comment by guylepage3** [comment]
@estermer what are all the FAQ.js changes that are occuring on this PR? shouldn't it just be a simple css change?

**Comment by guylepage3** [comment]
Also, it looks as though there are some directly targeted items instead of focusing on css classes. We want to utilize targeting classes as they are much more malleable.

I am needing to have a clean pr for this today. Is this something you can adjust? Please let me know, otherwise i will need to make the edit myself. Thank you sir.

**Comment by guylepage3** [comment]
See the following comment on the github issue.. https://github.com/blockstack/blockstack.org/issues/289#issuecomment-301272454

**Comment by estermer** [comment]
I can take a look. I made comments on the issue.

**Comment by guylepage3** [comment]
@estermer i'll take a look at this today and merge what works and what does not. do you have time to take a look at your css before 5pm (EST) today?

**Comment by estermer** [comment]
yeah i will look at it here before 5

**Comment by estermer** [comment]
were you referring to the `opening` and `closing` classes I created in terms of being to targeted?

**Comment by estermer** [comment]
if it is a rush to get done before 5, I dont think I have the time, but if you want me to work it through the week that would be fine with me.

**Comment by guylepage3** [comment]
looking into this now

**Comment by guylepage3** [comment]
@estermer i'm not able to merge this one in as there are too many customizations that are not standard to bootstrap. let's work on this for future PR's.

**Comment by estermer** [comment]
@guylepage3 ok that is fine, ping me sometime today and we can go over it together. It would be nice to get a better understanding of the expectations here. 👍

**Comment by guylepage3** [comment]
@estermer for sure.. i can show you how Bootstrap approached this and how I resolved it using the framework.

**Comment by estermer** [comment]
I do have a question regarding Bootstrap... is there a benefit to using/not using React Bootstrap?

**Comment by guylepage3** [comment]
@estermer can you pose this question on the forum? http://forum.blockstack.org

**Comment by guylepage3** [comment]
working on the merge now @estermer as i used some of your code.

**Comment by guylepage3** [comment]
@shea256 i've merged @estermer's changes into `design` here: https://github.com/blockstack/blockstack.org/commit/83da5547cc79fa49ec5b401b6e8ac8b31b5758d5

Please merge and push live. thank you.

**Comment by estermer** [comment]
@shea256 this should be ready to merge to master from design as per @guylepage3. :)

**Pull request merged**
