### PR TITLE
Install page fix

### LINKED ISSUE #290: breakage of install page on mobile
Install page breakage on mobile

screenshot 2017-04-25 17 12 45
screenshot 2017-04-25 17 15 58

### PR DESCRIPTION
**Pull request by estermer**
#290 

screen shot 2017-04-27 at 9 07 44 am

### CODE REVIEW

**Comment by estermer** [comment]
not sure how the firebase.json and app/docs changes made it in there, maybe I merged master in sometime.

**Comment by guylepage3** [comment]
@estermer we can ignore those as the are updates being fetched from the blockstack repo via Git Submodules and Gulp is automatically compiling them.

**Comment by estermer** [comment]
@guylepage3 this should be good to go.

**Comment by guylepage3** [comment]
@estermer can we get you to merge from `design`? that I believe is something we discussed in the contribution process. thank you sir.

**Comment by estermer** [comment]
Oh yes I forgot that this was prior to that

**Comment by estermer** [comment]
@guylepage3 this has been changed to `design` base

**Comment by guylepage3** [comment]
@estermer merged into `design`

**Pull request merged**
