### PR TITLE
Updated apps on homepage

### PR DESCRIPTION
**Pull request by cwackerfuss**
1. Keep Coins in Featured Apps and replace its listing in Crypto Portfolio Apps with Coinremix
2. Replace DotPodcast in Upcoming Apps with Misthos
3. Update Casa category to "Key Management" and change link to keys.casa

screen shot 2018-03-23 at 3 41 04 pm

### CODE REVIEW

**Comment by cwackerfuss** [comment]
cc @yknl @jackzampolin

**Comment by yknl** [comment]
Looks good to me! We should be merging into develop though.

**Comment by cwackerfuss** [comment]
Thanks! I'll merge to develop

**Comment by jackzampolin** [comment]
DO THE THINGS!

**Pull request merged**
