### PR TITLE
Update Downloads Page

### PR DESCRIPTION
**Pull request by jackzampolin**
Removes mention of the CLI from the downloads page.

### CODE REVIEW

**Comment by guylepage3** [comment]
@jackzampolin thanks for the pull request. Can we get you to pull from `develop` branch good sir? Thank you. 😄

**Comment by jackzampolin** [comment]
@guylepage3 I'm pretty sure this is from develop into develop. Am I wrong here?

**Comment by guylepage3** [comment]
@jackzampolin hmm.. looks like it.

**Comment by guylepage3** [comment]
@jackzampolin will merge this in now

**Comment by guylepage3** [comment]
@jackzampolin this pr has conflicts... can you resolve them please? thank you sir. :)

**Comment by jackzampolin** [comment]
Ok so when I put this up it was in proper format and mergeable. Someone has deleted the same lines I changed. Do we like not including the `Run a full node` section on the website or do we want to not include it?

**Comment by guylepage3** [comment]
@jackzampolin do you know who changed it?

**Comment by jackzampolin** [comment]
`git blame` indicates it was @shea256:

```
b80b822f (Ryan Shea  2017-04-15 19:45:37 -0400 73)                       </table>
b80b822f (Ryan Shea  2017-04-15 19:45:37 -0400 74)                     </div>
b80b822f (Ryan Shea  2017-04-15 19:45:37 -0400 75)                     <div>
f23ec6db (Ryan Shea  2017-04-18 18:02:42 -0400 76)                       <h3>Core Server + CLI</h3>
b80b822f (Ryan Shea  2017-04-15 19:45:37 -0400 77)                       <p>
bb3dc1d5 (Ryan Shea  2017-04-18 12:03:49 -0400 78)                         <a href={installationLinks.cliDevelopers} role="button"
b80b822f (Ryan Shea  2017-04-15 19:45:37 -0400 79)                           className="btn btn-outline-primary btn-block">
b80b822f (Ryan Shea  2017-04-15 19:45:37 -0400 80)                           Instructions on GitHub
b80b822f (Ryan Shea  2017-04-15 19:45:37 -0400 81)                         </a>
b80b822f (Ryan Shea  2017-04-15 19:45:37 -0400 82)                       </p>
b80b822f (Ryan Shea  2017-04-15 19:45:37 -0400 83)                     </div>
```

**Comment by jackzampolin** [comment]
There is also discussion going on about how integrate the Linux and Win installs into this process: https://github.com/blockstack/blockstack-browser/issues/806

**Comment by shea256** [comment]
Oh whoops sorry @jackzampolin I didn't see this PR. Feel free to take your changes and override. @larrysalibra can be the point person to merge and deploy.

**Comment by jackzampolin** [comment]
Thanks @shea256 I'll do that!

**Comment by guylepage3** [comment]
will merge this in now @jackzampolin

**Pull request merged**
