### PR TITLE
Fix FAQ Page

### PR DESCRIPTION
**Pull request by jackzampolin**
@guylepage3 This pull fixes the broken FAQ link

### CODE REVIEW

**Comment by shea256** [comment]
@jackzampolin Thanks! Can you please fix this line as well: https://github.com/blockstack/blockstack.org/blob/master/gulp/tasks/configFirebase.js#L106

**Comment by jackzampolin** [comment]
@shea256 Done!

**Comment by shea256** [comment]
@jackzampolin If we're going with /faqs instead of /faq then we need to have /faq redirect to /faqs. Any reason we're flipping this? Might just be easier to fix the link and have all /faqs links to go /faq.

**Comment by jackzampolin** [comment]
@shea256 Thats probably the better way to do that. I did it originally as `/faqs` because I thought that was the least changes that needed to be done but I didn't see there were only two links there! I've switched it back to `/faq`

**Comment by shea256** [comment]
ok sweet! merging.

**Pull request merged**
