### PR TITLE
global replacement of beta to alpha

### PR DESCRIPTION
**Pull request by guylepage3**

### CODE REVIEW

**Comment by guylepage3** [comment]
@shea256 there's something happening with the **Browser** link in the header. Can you take a look before merging?

**Comment by shea256** [comment]
@guylepage3 Sorry I didn't see this and I made the updates to "Alpha". I think I got them all but please let me know if there's one I missed.

**Comment by guylepage3** [comment]
@shea256 if you did a global replace we should be good and can close out this pr.

**Comment by shea256** [comment]
Great thanks, closing.

**Pull request closed without merging**
